apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

# patchesStrategicMerge:
# # - custom-env.yaml
# # - replica-and-rollout-strategy.yaml

images:
- name: yeasy/simple-web
  newName: nginx:latest
  newTag: red
  # newTag: blue
  # newTag: failure
