apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesStrategicMerge:
- custom-env.yaml
- replica-and-rollout-strategy.yaml

images:
- name: 
  newName: kodekloud/simple-webapp
  newTag: blue
  # newTag: green
