apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-bg
spec:
  selector:
    matchLabels:
      app: demo-app-bg
  template:
    metadata:
      labels:
        app: demo-app-bg
    spec:
      containers:
      - name: app
        image: yeasy/simple-web
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
